package com.its.sep.processes.installationprocess.handlers;
import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class RecordSimsDevicesInInventoryHandler implements WorkItemHandler {

  public void executeWorkItem(WorkItem workItem, WorkItemManager manager) {
    // extract parameters
    Object jobOrderInstance =  workItem.getParameter("jobOrderInstance");
    System.out.println("__RecordSimsDevicesInInventoryHandler____ Class " + jobOrderInstance.getClass() + "\n"+ jobOrderInstance.toString());
    //TODO Place WS Call here
    manager.completeWorkItem(workItem.getId(), null);
  }

  public void abortWorkItem(WorkItem workItem, WorkItemManager manager) {
    // Do nothing, notifications cannot be aborted
  }

}