package com.its.sep.processes.installationprocess.handlers;

import java.net.MalformedURLException;
import java.util.List;

import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UpdateDevicesSimsStatusInventoryHandler implements WorkItemHandler {

	public void executeWorkItem(WorkItem workItem, WorkItemManager manager) {
		// extract parameters
		Object jobOrderInstance = workItem.getParameter("jobOrderInstance");
		Object workOrderPackage = workItem.getParameter("wordOrderPackage");
		System.out.println("___UpdateDevicesSimsStatusInventoryHandler___ Class " + jobOrderInstance.getClass() + "\n"
				+ jobOrderInstance.toString());
		manager.completeWorkItem(workItem.getId(), null);
	}

	public void abortWorkItem(WorkItem workItem, WorkItemManager manager) {
		// Do nothing, notifications cannot be aborted
	}
}